export const ATTESTATION_REGISTRY_ABI = [
  {
    type: "event",
    name: "ClaimIssued",
    inputs: [
      { name: "claimId", type: "bytes32", indexed: true },
      { name: "subject", type: "address", indexed: true },
      { name: "issuer", type: "address", indexed: true },
      { name: "schemaId", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "function",
    name: "ISSUER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "REVOKER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "attest",
    inputs: [
      { name: "subject", type: "address", internalType: "address" },
      { name: "schemaId", type: "bytes32", internalType: "bytes32" },
      { name: "dataCommitment", type: "bytes32", internalType: "bytes32" },
      { name: "expiresAt", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "claimId", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revoke",
    inputs: [{ name: "claimId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getClaim",
    inputs: [{ name: "claimId", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      { name: "claimId", type: "bytes32", internalType: "bytes32" },
      { name: "subject", type: "address", internalType: "address" },
      { name: "schemaId", type: "bytes32", internalType: "bytes32" },
      { name: "issuer", type: "address", internalType: "address" },
      { name: "dataCommitment", type: "bytes32", internalType: "bytes32" },
      { name: "issuedAt", type: "uint256", internalType: "uint256" },
      { name: "expiresAt", type: "uint256", internalType: "uint256" },
      { name: "revoked", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isValid",
    inputs: [{ name: "claimId", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getActiveClaim",
    inputs: [
      { name: "subject", type: "address", internalType: "address" },
      { name: "schemaId", type: "bytes32", internalType: "bytes32" },
      { name: "issuer", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
] as const;
