export const ATTESTATION_REGISTRY_ABI = [
  {
    type: "function",
    name: "ISSUER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "REVOKER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "attest",
    inputs: [
      { name: "subject", type: "address", internalType: "address" },
      { name: "schemaId", type: "bytes32", internalType: "bytes32" },
      { name: "dataCommitment", type: "bytes32", internalType: "bytes32" },
      { name: "expiresAt", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "claimId", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revoke",
    inputs: [{ name: "claimId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "adminRevoke",
    inputs: [{ name: "claimId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getClaim",
    inputs: [{ name: "claimId", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      { name: "claimId", type: "bytes32", internalType: "bytes32" },
      { name: "subject", type: "address", internalType: "address" },
      { name: "schemaId", type: "bytes32", internalType: "bytes32" },
      { name: "issuer", type: "address", internalType: "address" },
      { name: "dataCommitment", type: "bytes32", internalType: "bytes32" },
      { name: "issuedAt", type: "uint256", internalType: "uint256" },
      { name: "expiresAt", type: "uint256", internalType: "uint256" },
      { name: "revoked", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isValid",
    inputs: [{ name: "claimId", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getIssuers",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getActiveClaim",
    inputs: [
      { name: "subject", type: "address", internalType: "address" },
      { name: "schemaId", type: "bytes32", internalType: "bytes32" },
      { name: "issuer", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "error",
    name: "ArcPass__NotIssuer",
    inputs: [{ name: "caller", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ArcPass__NotRevoker",
    inputs: [{ name: "caller", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ArcPass__ClaimNotFound",
    inputs: [{ name: "claimId", type: "bytes32", internalType: "bytes32" }],
  },
  {
    type: "error",
    name: "ArcPass__ClaimAlreadyRevoked",
    inputs: [{ name: "claimId", type: "bytes32", internalType: "bytes32" }],
  },
  {
    type: "error",
    name: "ArcPass__ActiveClaimExists",
    inputs: [
      { name: "subject", type: "address", internalType: "address" },
      { name: "schemaId", type: "bytes32", internalType: "bytes32" },
      { name: "issuer", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "ArcPass__ClaimExpired",
    inputs: [
      { name: "claimId", type: "bytes32", internalType: "bytes32" },
      { name: "expiredAt", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ArcPass__InvalidSubject",
    inputs: [],
  },
  {
    type: "error",
    name: "ArcPass__InvalidSchemaId",
    inputs: [],
  },
  {
    type: "error",
    name: "ArcPass__ZeroAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "ArcPass__InvalidBatchSize",
    inputs: [{ name: "size", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "ArcPass__EmptyData",
    inputs: [],
  },
  {
    type: "error",
    name: "ArcPass__InvalidExpiry",
    inputs: [],
  },
] as const;
